### ISSUE TITLE
你这个部署在k8s下的方案不好。

### ISSUE THREAD

**Issue by rojamajor** [fuluteam/ICH.Snowflake#3]
直接部署为statefulset就行了，都是按照序号启动的，然后工作机器id设置为序号，几行代码事情。

**Comment by billsking** [comment]
你说的方案挺好。 但可能并不适用所有场景。 比如，不用k8s的场景，再比如，用的k8s,但旧服务部署的是无状态的，那需要对服务部署方式进行调整，会带来一定的风险。
