### ISSUE TITLE
算法会产生负数的雪花Id

### ISSUE THREAD

**Issue by xingwen1987** [fuluteam/ICH.Snowflake#4]
算法会产生负数的雪花Id

**Comment by billsking** [comment]
能提供下代码片段吗？具体什么场景？

**Comment by xingwen1987** [comment]
> 能提供下代码片段吗？具体什么场景？

![image](https://user-images.githubusercontent.com/15207100/144778899-8dc4e927-30b9-4c20-9b96-dce0024e9b75.png)

为了提高高并发下生成的精度，时间戳我没有除 10000
这么做的原因是发现在 foreach 循环中，对一个简单模型赋值时，会出现重复 Id
![image](https://user-images.githubusercontent.com/15207100/144779925-42f9afa7-28c3-46f0-b10f-048bc3dd5eb6.png)

此时，生成的 Id 是负的

workId=81
_workIdLength=10
_indexLength=12
_maxWorkId=1024

**Comment by billsking** [comment]
其实你完全没必要考虑精度的问题，我现在的时间戳已经是毫秒级的了，毫秒级最大支持4096个id，也就是每秒最大可生成4096000个id，我觉得就算是淘宝双十一这个数量也够用了。
而且，你调整了时间戳的长度，那么已经超出了41位长度了，那总长度也超出了64位，所以出现负数是正常的。

**Comment by xingwen1987** [comment]
> 其实你完全没必要考虑精度的问题，我现在的时间戳已经是毫秒级的了，毫秒级最大支持4096个id，也就是每秒最大可生成4096000个id，我觉得就算是淘宝双十一这个数量也够用了。 而且，你调整了时间戳的长度，那么已经超出了41位长度了，那总长度也超出了64位，所以出现负数是正常的。

目前我们实测，这个 Id 在内存中进行并发 foreach 的时候，确实会出现重复现象，我把 long 调整为了 ulong，已解决问题

**Comment by billsking** [comment]
重复的问题应该是由于 #2 导致的。 此bug已修复。 你可以拉取下最新的代码再试试。
