### ISSUE TITLE
RefreshAliveInterval设置为1小时会不会太长了？

### ISSUE THREAD

**Issue by li-zheng-hao** [fuluteam/ICH.Snowflake#6]
文档中的配置项有一条是刷新存活时间的timestamp：
```
builder.Services.AddSnowflakeWithRedis(opt =>
{
    opt.RefreshAliveInterval = TimeSpan.FromHours(1);
});
```
这里每1小时才刷新一次时间戳，但是取workid又是从五分钟前开始取的，如果512个节点都被使用了且都没在5分钟内刷新时间戳，这个时候不是会直接把已经在使用的某一个workid给返回吗

**Comment by li-zheng-hao** [comment]
还有一个问题，如果workid的上限是512个的话，假设有257个节点正在运行，使用了257个workid，那么如果257个节点同时重启，需要重新获取257个未被使用的workid，而查询可用workid的方法是查询score在0到5分钟前时间戳值的范围，这个范围应该是只有255个的，因此会有2个节点出现无法获取到新workid的情况，这样算的话假设workid位的长度设置为9，那么实际上只有256个workid是可以同时使用的

**Comment by billsking** [comment]
你说的这种场景比较极端，个人觉得出现场景很低。可以担心，建议把RefreshAliveInterval时间设小点， 比如1分钟。
